### ISSUE TITLE
Errors building project

### ISSUE THREAD

**Issue by lu10539** [jmfieldman/Merge#2]
I got some errors that the file `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a` is not found and the linker command failed with exit code -1.
```
File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jmfieldman** [comment]
Hi Lucas,

Thanks so much for taking an interest in this project! Unfortunately, it was written 10 years ago and I'm definitely not maintaining it anymore.  It seems like whatever settings were used for ARC back then aren't compatible with modern toolchains :(

You may need to figure this one out on your own.

Best,
Jason
